apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Store
metadata:
  name: store-oras
spec:
  name: oras
  parameters:
    cosign-enabled: false  
    cacheEnabled: true
    capacity: 100
    keyNumber: 10000
    ttl: 10
    useHttp: true  
    authProvider:
      name: k8Secrets
      secrets: 
      - secretName: ratify-dockerconfig