apiVersion: config.ratify.deislabs.io/v1alpha1
kind: Store
metadata:
  name: store-oras
spec:
  name: oras
  parameters:
    cacheEnabled: true
    capacity: 100
    cosignEnabled: false
    keyNumber: 10000
    ttl: 10
    useHttp: true
