{{ include "ratify.assignGKVersion" . }}
kind: Assign
metadata:
  name: mutate-pod-image
spec:
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["*"]
      kinds: ["Pod"]
    excludedNamespaces:
      {{ include "ratify.assignExcludedNamespaces" . | nindent 6 }}
  applyTo:
  - groups: [""]
    kinds: ["Pod"]
    versions: ["v1"]
  location: "spec.containers[name:*].image"
  parameters:
    assign:
      externalData:
        provider: ratify-mutation-provider
---
{{ include "ratify.assignGKVersion" . }}
kind: Assign
metadata:
  name: mutate-workload-image
spec:
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["apps", "batch"]
      kinds: ["Deployment", "ReplicaSet", "StatefulSet", "DaemonSet", "Job"]
    excludedNamespaces:
      {{ include "ratify.assignExcludedNamespaces" . | nindent 6 }}
  applyTo:
  - groups: ["apps", "batch"]
    kinds: ["Deployment", "ReplicaSet", "StatefulSet", "DaemonSet", "Job", "ReplicationController"]
    versions: ["v1"]
  location: "spec.template.spec.containers[name:*].image"
  parameters:
    assign:
      externalData:
        provider: ratify-mutation-provider
---
{{ include "ratify.assignGKVersion" . }}
kind: Assign
metadata:
  name: mutate-cronjob-image
spec:
  match:
    scope: Namespaced
    kinds:
    - apiGroups: ["batch"]
      kinds: ["CronJob"]
    excludedNamespaces:
      {{ include "ratify.assignExcludedNamespaces" . | nindent 6 }}
  applyTo:
  - groups: ["batch"]
    kinds: ["CronJob"]
    versions: ["v1"]
  location: "spec.jobTemplate.spec.template.spec.containers[name:*].image"
  parameters:
    assign:
      externalData:
        provider: ratify-mutation-provider
 