apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ratify.fullname" . }}-configuration
data:
  config.json: |
    {
      "executor": {
        "verificationRequestTimeout": {{ .Values.provider.timeout.validationTimeoutSeconds | int | mul 1000 | add -100 }},
        "mutationRequestTimeout": {{ .Values.provider.timeout.mutationTimeoutSeconds | int | mul 1000 | add -50 }}
      },
      "store": {
        "version": "1.0.0",
        "useHttp": {{ .Values.oras.useHttp }},
        "plugins": [
            {
                "name": "oras"
                {{- if .Values.cosign.enabled }}
                ,
                "cosignEnabled": true
                {{- end }}
                {{- if .Values.oras.authProviders.azureWorkloadIdentityEnabled }}
                ,
                "authProvider": {
                    "name": "azureWorkloadIdentity"
                }
                {{- end }}
                {{- if .Values.oras.authProviders.azureManagedIdentityEnabled }}
                ,
                "authProvider": {
                    "name": "azureManagedIdentity",
                    "clientID": {{ .Values.azureManagedIdentity.clientId }}
                }
                {{- end }}
                {{- if .Values.oras.authProviders.k8secretsEnabled }}
                ,
                "authProvider": {
                    "name": "k8Secrets",
                    "serviceAccountName": "{{ include "ratify.serviceAccountName" . }}"
                }
                {{- end }}
                {{- if .Values.oras.authProviders.awsEcrBasicEnabled }}
                ,
                "authProvider": {
                    "name": "awsEcrBasic"
                }
                {{- end }}
            }
        ]
      },
      "policy": {
        "version": "1.0.0",
        "plugin": {
            "name": "configPolicy"
        }
      },
      "verifier": {
          "version": "1.0.0",
          "plugins": [
            {
                "name":"notaryv2",
                "artifactTypes" : "application/vnd.cncf.notary.signature",
                "verificationCertStores": {
                  "certs":[
                    {{- if .Values.akvCertConfig.enabled }}
                    "certstore-akv"
                    {{- else }}
                    "{{ include "ratify.fullname" . }}-notary-inline-cert"
                    {{- end }}
                   ]
                },
                "trustPolicyDoc": {
                  "version": "1.0",
                  "trustPolicies": [
                    {
                      "name": "default",
                      "registryScopes": [ "*" ],
                      "signatureVerification": {
                        "level" : "strict" 
                      },
                      "trustStores": ["ca:certs"],
                      "trustedIdentities": ["*"]
                    }
                  ]
                }
            {{- if .Values.cosign.enabled }}
            },
            {
                "name": "cosign",
                "artifactTypes": "org.sigstore.cosign.v1",
                "key": "/usr/local/ratify-certs/cosign/cosign.pub"
            {{- end }}
            }
          ]
      }
    }
