{{- $subject := printf "/CN=ratify.%s" .Release.Namespace -}}
{{- $dns := printf "ratify.%s" .Release.Namespace -}}
{{- $ca := genCA "/O=Ratify/CN=Ratify Root CA" 365 -}}
{{- $cert := genSignedCert $subject nil (list $dns) 365 $ca -}}

---

{{ include "ratify.providerGKVersion" . }}
kind: Provider
metadata:
  name: ratify-provider
spec:
  url: https://{{ include "ratify.fullname" .}}.{{ .Release.Namespace }}:6001/ratify/gatekeeper/v1/verify
  timeout: {{ required "You must provide .Values.provider.timeout.validationTimeoutSeconds" .Values.provider.timeout.validationTimeoutSeconds }}
  {{ include "ratify.providerCabundle" (list . $ca) | nindent 2}}

---

{{ include "ratify.providerGKVersion" . }}
kind: Provider
metadata:
  name: ratify-mutation-provider
spec:
  url: https://{{ include "ratify.fullname" .}}.{{ .Release.Namespace }}:6001/ratify/gatekeeper/v1/mutate
  timeout: {{ required "You must provide .Values.provider.timeout.mutationTimeoutSeconds" .Values.provider.timeout.mutationTimeoutSeconds }}
  {{ include "ratify.providerCabundle" (list . $ca) | nindent 2}}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-tls
data:
  {{ include "ratify.tlsSecret" (list . $cert) | nindent 2}}
