{{- if .Values.cosign.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ratify.fullname" . }}-cosign-certificate
data:
  cosign.pub: {{ .Values.cosign.key | b64enc | quote }}
{{- end }}
 